### ISSUE TITLE
Enabled on all samvera and samvera-labs repos?

### ISSUE THREAD

**Issue by cjcolvar** [samvera-labs/cla-bot#3]
@escowles @heathergreerklein Is `cla-bot` enabled on all samvera and samvera-labs repos now?  I'm not seeing a `cla-signed` label being added to new hyrax PRs.

**Comment by escowles** [comment]
@cjcolvar It's enabled on `samvera-labs`, but not `samvera` yet — I didn't see it in the settings or see the `cla-signed` label on PRs — can you point me to one in hyrax? My plan was to confirm that the latest formatting updates work in `samvera-labs`, and then enable in the `samvera` org.

**Comment by cjcolvar** [comment]
Cool, that matches with what I'm seeing.  I was asking because of a [PR to documentation](https://github.com/samvera/samvera.github.io/pull/439#discussion_r799424781) about the review process.

Thanks for doing this work!  This new process is much better!
